import React, { useState, useEffect } from 'react';
import { Label, TextField } from "@fluentui/react";
import { FiHelpCircle } from 'react-icons/fi'
import styles from "./ResponseTempSlider.module.css";

interface Props {
  className?: string;
  onChange: (newValue: number) => void;
  value?: number;
}

const tooltipHtml = `
This parameter determines the creativity and diversity of the text generated by the GPT model.<br /><br />
A higher temperature value (e.g., 1.0) leads to more diverse and creative text, while a lower value
(e.g., 0.0) results in more focused and deterministic text.`;


export const ResponseTempSlider = ({ className, onChange, value = 0 }: Props) => {
  const [sliderValue, setSliderValue] = useState<number>(value);
  const [displayValue, setDisplayValue] = useState<string>(value.toFixed(2));

  useEffect(() => {
    setSliderValue(value);
    setDisplayValue(value.toFixed(2));
  }, [value]);

  const updateValue = (newValue: number) => {
    const boundedValue = Math.max(0, Math.min(newValue, 1));
    setSliderValue(boundedValue);
    setDisplayValue(boundedValue.toFixed(2));
    onChange(boundedValue);
  };

  const handleSliderChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = parseFloat(event.target.value);
    setSliderValue(newValue);
    setDisplayValue(newValue.toFixed(2));
    onChange(newValue);
  };

  const handleInputChange = (event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
    if (newValue !== undefined) {
      setDisplayValue(newValue);
    }
  };

  const validateAndRound = (input: string) => {
    let numericValue = parseFloat(input);
    if (isNaN(numericValue)) {
      numericValue = 0; // Default to 0 if input is not a number
    }
    return Math.max(0, Math.min(numericValue, 1));
  };

  const handleInputBlur = () => {
    updateValue(validateAndRound(displayValue));
  };

  return (
    <div className={`${styles.container} ${className ?? ""}`}>
      <Label>Response Temperature&nbsp;
        <FiHelpCircle
          data-tooltip-id="ResponseTempSlider-tooltip"
          data-tooltip-html={tooltipHtml}
        />
      </Label>
      <TextField
        className={styles.responseTempValue}
        value={displayValue}
        onChange={handleInputChange}
        onBlur={handleInputBlur}
      />
      <input
        className={`${styles.tempSlider}`}
        type="range"
        value={sliderValue}
        step={0.01}
        min={0.00}
        max={1.00}
        onChange={handleSliderChange}
      />
    </div>
  );
};
